
package ec.edu.espe.arquitectura.wstest.service;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlumnoWS", targetNamespace = "http://service.wstest.arquitectura.espe.edu.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlumnoWS {


    /**
     * 
     * @return
     *     returns java.util.List<ec.edu.espe.arquitectura.wstest.service.Alumno>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAlumnos", targetNamespace = "http://service.wstest.arquitectura.espe.edu.ec/", className = "ec.edu.espe.arquitectura.wstest.service.ObtenerAlumnos")
    @ResponseWrapper(localName = "obtenerAlumnosResponse", targetNamespace = "http://service.wstest.arquitectura.espe.edu.ec/", className = "ec.edu.espe.arquitectura.wstest.service.ObtenerAlumnosResponse")
    @Action(input = "http://service.wstest.arquitectura.espe.edu.ec/AlumnoWS/obtenerAlumnosRequest", output = "http://service.wstest.arquitectura.espe.edu.ec/AlumnoWS/obtenerAlumnosResponse")
    public List<Alumno> obtenerAlumnos();

    /**
     * 
     * @param al
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "agregarAlumno", targetNamespace = "http://service.wstest.arquitectura.espe.edu.ec/", className = "ec.edu.espe.arquitectura.wstest.service.AgregarAlumno")
    @Action(input = "http://service.wstest.arquitectura.espe.edu.ec/AlumnoWS/agregarAlumno")
    public void agregarAlumno(
        @WebParam(name = "al", targetNamespace = "")
        Alumno al);

    /**
     * 
     * @param cedula
     * @return
     *     returns ec.edu.espe.arquitectura.wstest.service.Alumno
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerAlumnoPorCedula", targetNamespace = "http://service.wstest.arquitectura.espe.edu.ec/", className = "ec.edu.espe.arquitectura.wstest.service.ObtenerAlumnoPorCedula")
    @ResponseWrapper(localName = "obtenerAlumnoPorCedulaResponse", targetNamespace = "http://service.wstest.arquitectura.espe.edu.ec/", className = "ec.edu.espe.arquitectura.wstest.service.ObtenerAlumnoPorCedulaResponse")
    @Action(input = "http://service.wstest.arquitectura.espe.edu.ec/AlumnoWS/obtenerAlumnoPorCedulaRequest", output = "http://service.wstest.arquitectura.espe.edu.ec/AlumnoWS/obtenerAlumnoPorCedulaResponse")
    public Alumno obtenerAlumnoPorCedula(
        @WebParam(name = "cedula", targetNamespace = "")
        String cedula);

}
