
package ec.edu.espe.arquitectura.wstest.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlumnoWS", targetNamespace = "http://service.wstest.arquitectura.espe.edu.ec/", wsdlLocation = "http://localhost:8080/wstest-web/AlumnoWS?wsdl")
public class AlumnoWS_Service
    extends Service
{

    private final static URL ALUMNOWS_WSDL_LOCATION;
    private final static WebServiceException ALUMNOWS_EXCEPTION;
    private final static QName ALUMNOWS_QNAME = new QName("http://service.wstest.arquitectura.espe.edu.ec/", "AlumnoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wstest-web/AlumnoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALUMNOWS_WSDL_LOCATION = url;
        ALUMNOWS_EXCEPTION = e;
    }

    public AlumnoWS_Service() {
        super(__getWsdlLocation(), ALUMNOWS_QNAME);
    }

    public AlumnoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALUMNOWS_QNAME, features);
    }

    public AlumnoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, ALUMNOWS_QNAME);
    }

    public AlumnoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALUMNOWS_QNAME, features);
    }

    public AlumnoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlumnoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlumnoWS
     */
    @WebEndpoint(name = "AlumnoWSPort")
    public AlumnoWS getAlumnoWSPort() {
        return super.getPort(new QName("http://service.wstest.arquitectura.espe.edu.ec/", "AlumnoWSPort"), AlumnoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlumnoWS
     */
    @WebEndpoint(name = "AlumnoWSPort")
    public AlumnoWS getAlumnoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wstest.arquitectura.espe.edu.ec/", "AlumnoWSPort"), AlumnoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALUMNOWS_EXCEPTION!= null) {
            throw ALUMNOWS_EXCEPTION;
        }
        return ALUMNOWS_WSDL_LOCATION;
    }

}
